[tool.nixpacks]
providers = ["python"]

[tool.nixpacks.phases.setup]
nixPkgs = ["python312"]

[tool.nixpacks.phases.build]
cmds = ["pip install -r requirements.txt"]

[tool.nixpacks.start]
cmd = "uvicorn server:app --host 0.0.0.0 --port ${PORT:-8000}"
